<?php
declare(strict_types=1);require __DIR__.'/lib/FlightStats.php';
$parsed=parseFlights(file_get_contents(__DIR__.'/data/Flugdatenbank.md'));$airports=json_decode(file_get_contents(__DIR__.'/data/airports.json'),true,512,JSON_THROW_ON_ERROR);$stats=flightStats($parsed,$airports);
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}function route($s){return h($s['from'].' → '.$s['to']);}
$groups=[];foreach($stats['enriched'] as $s)$groups[$s['status']][$s['year'].'|'.$s['trip']][]=$s;
?><!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Flugbuch – Adam Dolinsky</title><meta name="description" content="80 Flugsegmente, 48 Flughäfen und eine persönliche Reisechronik auf einer interaktiven Weltkarte."><meta property="og:title" content="Flugbuch – Adam Dolinsky"><meta property="og:description" content="Ein persönliches Reise-Editorial in Zahlen und Routen."><meta property="og:type" content="website"><link rel="stylesheet" href="/assets/css/travel.css"></head><body>
<header class="mast"><a href="/">AD / Portfolio</a><span>Persönliches Flugbuch</span><span>2023—<?=date('Y')?></span></header>
<main><section class="hero"><p class="eyebrow">Unterwegs / Ausgabe 01</p><h1>Die Welt<br><em>in Linien.</em></h1><p class="intro">Eine persönliche Kartografie aus Abflügen, Umwegen und Ankünften. Direkt aus dem Flugtagebuch gerechnet.</p><div class="hero-stats"><div><strong><?=count($stats['completed'])?></strong><span>geflogene Segmente</span></div><div><strong><?=number_format($stats['total'],0,"’","’")?></strong><span>Kilometer in der Luft</span></div><div><strong><?=count($stats['used'])?></strong><span>verschiedene Flughäfen</span></div></div></section>
<section class="atlas"><div class="section-head"><div><p class="eyebrow">Route Atlas</p><h2>Spuren über<br>dem Globus</h2></div><button id="plannedToggle" aria-pressed="true">Geplante Routen ausblenden</button></div><svg id="map" viewBox="0 0 1000 500" role="img" aria-label="Weltkarte mit Flugrouten"><rect width="1000" height="500" fill="#dce4df"/><g class="grid"><?php for($x=0;$x<=1000;$x+=125) echo "<path d='M$x 0V500'/>";for($y=0;$y<=500;$y+=100) echo "<path d='M0 $y H1000'/>";?></g><g class="routes"><?php foreach($stats['enriched'] as $s):$a=$airports[$s['from']];$b=$airports[$s['to']];$x1=($a['lon']+180)/360*1000;$y1=(90-$a['lat'])/180*500;$x2=($b['lon']+180)/360*1000;$y2=(90-$b['lat'])/180*500;$planned=$s['status']==='planned';if(abs($x2-$x1)>500){if($x1<$x2)$x1+=1000;else $x2+=1000;}?><path class="route <?=$planned?'planned':''?>" d="M<?=round($x1,1)?> <?=round($y1,1)?> Q<?=round(($x1+$x2)/2,1)?> <?=round(min($y1,$y2)-25,1)?> <?=round($x2,1)?> <?=round($y2,1)?>"/><path class="route <?=$planned?'planned':''?>" d="M<?=round($x1-1000,1)?> <?=round($y1,1)?> Q<?=round(($x1+$x2)/2-1000,1)?> <?=round(min($y1,$y2)-25,1)?> <?=round($x2-1000,1)?> <?=round($y2,1)?>"/><?php endforeach?></g><g><?php foreach($stats['used'] as $code=>$_):$a=$airports[$code];?><circle cx="<?=round(($a['lon']+180)/360*1000,1)?>" cy="<?=round((90-$a['lat'])/180*500,1)?>" r="3"><title><?=h($code.' · '.$a['city'])?></title></circle><?php endforeach?></g></svg><p class="caption">Mercatorfreie, schematische Projektion · Linien an der Datumsgrenze werden umgebrochen.</p></section>
<section class="numbers"><article><span>01 / Distanz</span><h2><?=number_format($stats['total']/40075,1,',','')?>×</h2><p>um den Äquator – dieselbe Strecke am Boden.</p></article><article><span>02 / Extreme</span><h3><?=route($stats['longest'])?></h3><p>Längstes Segment · <?=number_format($stats['longest']['distance'],0,"’","’")?> km</p><h3><?=route($stats['shortest'])?></h3><p>Kürzestes Segment · <?=number_format($stats['shortest']['distance'],0,"’","’")?> km</p></article><article><span>03 / Drehkreuze</span><?php $top=array_slice($stats['counts'],0,5,true);foreach($top as $code=>$n):?><div class="rank"><b><?=h($code)?></b><i style="--n:<?=$n?>"></i><small><?=$n?> Berührungen</small></div><?php endforeach?></article></section>
<section class="timeline"><div class="section-head"><div><p class="eyebrow">Chronologie</p><h2>Reisen, nicht<br>nur Strecken</h2></div><div class="years"><?php foreach($stats['years'] as $y=>$n):?><span><b><?=$y?></b> <?=$n?></span><?php endforeach?></div></div><?php foreach(['completed'=>'Durchgeführt','planned'=>'Geplant'] as $status=>$label):?><div class="status-block <?=$status?>"><h3><?=$label?> <sup><?=count($groups[$status]??[])?></sup></h3><?php foreach($groups[$status]??[] as $key=>$segments):[$year,$trip]=explode('|',$key,2);?><article><time><?=$year?></time><div><h4><?=h($trip)?></h4><p><?php foreach($segments as $i=>$s):?><span><?=route($s)?> <small><?=number_format($s['distance'],0,"’","’")?> km</small></span><?php endforeach?></p></div></article><?php endforeach?></div><?php endforeach?></section>
<?php if($parsed['memories']):?><aside class="memories"><p class="eyebrow">Randnotizen</p><?php foreach($parsed['memories'] as $m):?><blockquote>“<?=h($m['note'])?>”<cite><?=route($m)?></cite></blockquote><?php endforeach?></aside><?php endif?></main><footer class="end"><a href="/">← Zurück zum Portfolio</a><span>Datenstand aus Flugdatenbank.md</span></footer><script src="/assets/js/travel.js"></script></body></html>
