<?php
require __DIR__.'/lib/FlightStats.php';
try { $d=FlightStats::load(__DIR__.'/data/Flugdatenbank.md',__DIR__.'/data/airports.json'); } catch(Throwable $e) { http_response_code(500); exit('Reisedaten konnten nicht geladen werden.'); }
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');} function km($v){return number_format((float)$v,0,',','.').' km';}
$top=array_slice($d['usage'],0,5,true); $maxYear=max($d['years']); $groups=[]; foreach($d['segments'] as $s) $groups[$s['status'].'|'.$s['year'].'|'.$s['trip']][]=$s;
$map=['segments'=>$d['segments'],'airports'=>$d['usedAirports']];
?>
<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Reise-Logbuch | Adam Dolinsky</title><meta name="description" content="80 Flugsegmente, 48 Flughäfen und die Geschichten dazwischen – Adams persönliches Reise-Logbuch.">
<meta property="og:title" content="Reise-Logbuch | Adam Dolinsky"><meta property="og:description" content="Flugrouten, Distanzen und Reisegeschichten auf einer interaktiven Weltkarte."><meta property="og:type" content="website"><link rel="stylesheet" href="/assets/css/travel.css"></head>
<body id="top"><header class="travel-nav"><a href="/" class="wordmark" aria-label="Zurück zum Portfolio">AD<span>/</span>LOG</a><nav aria-label="Seitennavigation"><a href="#karte">Karte</a><a href="#chronik">Chronik</a><a class="back" href="/">Portfolio ↗</a></nav></header><main>
<section class="hero"><div class="eyebrow">Persönliches Flugarchiv · 2023—<?=h(array_key_last($d['years']))?></div><h1>Unterwegs zählt<br><em>jede Verbindung.</em></h1><p>Ein fortlaufendes Logbuch aus Flughäfen, Umwegen und Erinnerungen – direkt aus meiner Flugdatenbank neu berechnet.</p><div class="hero-rule"><span><?=count($d['completed'])?> geflogene Segmente</span><span><?=count($d['planned'])?> als Nächstes</span><span>Datenstand <?=date('d.m.Y',filemtime(__DIR__.'/data/Flugdatenbank.md'))?></span></div></section>
<section class="numbers" aria-label="Kennzahlen"><article class="number number--primary"><small>Zurückgelegte Luftlinie</small><strong><?=km($d['distance'])?></strong><p>Das entspricht <?=number_format($d['earths'],1,',','.')?> Erdumrundungen am Äquator.</p></article><article class="number"><small>Flughäfen im Logbuch</small><strong><?=count($d['usedAirports'])?></strong><p>Von <?=h($d['usedAirports']['GEA']['city'])?> bis <?=h($d['usedAirports']['NOU']['city'])?> – zwei Airports, eine Stadt.</p></article><article class="number"><small>Weiteste Etappe</small><strong><?=h($d['longest']['from'])?> → <?=h($d['longest']['to'])?></strong><p><?=km($d['longest']['distance'])?></p></article><article class="number"><small>Kürzeste Etappe</small><strong><?=h($d['shortest']['from'])?> → <?=h($d['shortest']['to'])?></strong><p><?=km($d['shortest']['distance'])?></p></article></section>
<section class="map-section" id="karte"><div class="section-head"><div><span class="kicker">01 / ROUTENATLAS</span><h2>Die Welt, verbunden</h2></div><div class="legend"><span><i></i> durchgeführt</span><span><i class="planned"></i> geplant</span></div></div><div class="map-wrap"><svg id="routeMap" viewBox="0 0 1000 500" role="img" aria-label="Weltkarte mit allen Flugrouten"><path class="land" d="M58 112l66-55 103 18 43 59-35 34-60-14-28 62-47-17-20-42zm207 132 56 28 31 83-20 89-38-57-18-82zm269-153 76-40 176 18 137 76-23 50-75-10-41 48-69-25-31 53-73-29-42-68-62-8-40-47zm208 186 59-20 64 44-11 58-85 21-51-43z"/><g id="routes"></g><g id="points"></g></svg><div class="map-note">Routen werden an der Datumsgrenze geteilt – statt unnatürlich quer über die Karte zu laufen.</div></div></section>
<section class="analysis"><div><span class="kicker">02 / MUSTER</span><h2>Wo Wege sich kreuzen</h2><ol class="ranking"><?php foreach($top as $code=>$count):?><li><b><?=h($code)?></b><span><?=h($d['airports'][$code]['city'])?></span><meter min="0" max="<?=max($top)?>" value="<?=$count?>"></meter><em><?=$count?>×</em></li><?php endforeach?></ol></div><div class="years"><h3>Segmente nach Jahr</h3><?php foreach($d['years'] as $year=>$count):?><div class="year"><span><?=$year?></span><div><i style="width:<?=round($count/$maxYear*100)?>%"></i></div><b><?=$count?></b></div><?php endforeach?></div></section>
<?php if($d['memories']):?><aside class="memory"><span>Randnotizen aus dem Logbuch</span><?php foreach($d['memories'] as $m):?><blockquote><b><?=h($m['from'])?> → <?=h($m['to'])?></b> <?=h(trim($m['text'],'„“'))?></blockquote><?php endforeach?></aside><?php endif?>
<section class="timeline" id="chronik"><div class="section-head"><div><span class="kicker">03 / CHRONIK</span><h2>Reisen, Segment für Segment</h2></div><button id="togglePlanned" type="button" aria-pressed="true">Geplante ausblenden</button></div><?php foreach($groups as $key=>$items): [$status,$year,$trip]=explode('|',$key,3);?><article class="journey <?=$status==='planned'?'is-planned':''?>"><header><time><?=$year?></time><div><h3><?=h($trip)?></h3><p><?=count($items)?> Segment<?=count($items)>1?'e':''?> · <?=km(array_sum(array_column($items,'distance')))?></p></div><span><?=$status==='planned'?'geplant':'geflogen'?></span></header><div class="route-list"><?php foreach($items as $s):?><div><b><?=h($s['from'])?></b><i>→</i><b><?=h($s['to'])?></b><small><?=km($s['distance'])?></small></div><?php endforeach?></div></article><?php endforeach?></section>
</main><footer class="travel-footer"><b>AD/LOG</b><p>Daten werden bei jedem Aufruf aus <code>Flugdatenbank.md</code> berechnet.</p><a href="#top">Nach oben ↑</a></footer>
<script type="application/json" id="mapData"><?=json_encode($map,JSON_HEX_TAG|JSON_UNESCAPED_UNICODE)?></script><script src="/assets/js/travel.js"></script></body></html>
